"""empty message

Revision ID: 31e529af20c1
Revises: aeb7b6c2f3dd
Create Date: 2019-02-24 16:31:02.717512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e529af20c1'
down_revision = 'aeb7b6c2f3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('core_id', sa.Numeric(), nullable=True))
    op.create_unique_constraint(None, 'device', ['core_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='unique')
    op.drop_column('device', 'core_id')
    # ### end Alembic commands ###
