"""empty message

Revision ID: 514553bc32ad
Revises: 
Create Date: 2019-02-09 21:57:43.704444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514553bc32ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Numeric(), nullable=False),
    sa.Column('longatuide', sa.Numeric(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('device', sa.Numeric(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=True),
    sa.Column('last_contacted', sa.TIMESTAMP(), nullable=True),
    sa.Column('contact_method', sa.Enum('sms', 'phone', 'both', name='contact_method'), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_phone_number'), 'subscriber', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriber_phone_number'), table_name='subscriber')
    op.drop_table('subscriber')
    op.drop_table('device')
    # ### end Alembic commands ###
