"""empty message

Revision ID: 7ad18f1c26a1
Revises: f25a4ab02f87
Create Date: 2019-02-27 23:20:29.075365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad18f1c26a1'
down_revision = 'f25a4ab02f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device', sa.Integer(), nullable=False),
    sa.Column('core_id', sa.Numeric(), nullable=False),
    sa.Column('reading_cm', sa.Integer(), nullable=False),
    sa.Column('reading_reported', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_reading')
    # ### end Alembic commands ###
