"""empty message

Revision ID: 8cbc2eb14356
Revises: 514553bc32ad
Create Date: 2019-02-09 22:39:16.531401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cbc2eb14356'
down_revision = '514553bc32ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriber', 'contact_method',
               existing_type=postgresql.ENUM('sms', 'phone', 'both', name='contact_method'),
               nullable=False)
    op.alter_column('subscriber', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriber', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriber', 'contact_method',
               existing_type=postgresql.ENUM('sms', 'phone', 'both', name='contact_method'),
               nullable=True)
    # ### end Alembic commands ###
