"""empty message

Revision ID: aeb7b6c2f3dd
Revises: 8cbc2eb14356
Create Date: 2019-02-11 19:02:59.396097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb7b6c2f3dd'
down_revision = '8cbc2eb14356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'name')
    # ### end Alembic commands ###
